FDP-2849: initial setup gitops
OSGP/gxf-gitops pull request #1
Opened 2024-12-16 09:02 UTC by JelleHoffman

2025-03-20 11:31 UTC, paulusalliander approved these changes

2025-03-20 11:31 UTC, paulusalliander commented on generate-secrets.sh
> +  echo "sup3r_s3cr3t"
Je password in je script hebben is niet zo'n goed plan, beter dit aan te leveren via stdin of .env of andere externe bron.

2025-03-20 11:31 UTC, paulusalliander commented on generate-secrets.sh
> +  openssl req -new -newkey rsa:4096 -passout pass:"${key_passphrase}" \
Misschien kun je overwegen iets anders dan rsa te gebruiken. Aangezien dit self signed certs zijn en nog lang geen 2030 niet zo belangrijk. 
https://fullcirclesecurity.org/2024/11/26/nist-announces-the-end-of-rsa-and-ecdsa/#:~:text=In%20a%20significant%20shift%20for%20cyber%20security%2C%20NIST,by%202030%2C%20with%20a%20full%20disallowance%20by%202035.

2025-03-20 11:31 UTC, paulusalliander commented on charts/gxf-platform/templates/httpd/config.yaml
> +  httpd.conf: |
Oef, voor nu prima om te embedden, maar overweeg httpd.conf te laden uit een externe file --set-file
https://helm.sh/docs/helm/helm_install/#:~:text=You%20can%20use%20'%2D%2Dset,arrays)%20from%20the%20command%20line.
https://devops.stackexchange.com/questions/18393/how-do-i-include-a-file-in-a-helm-config-map

2025-03-20 11:31 UTC, paulusalliander commented on charts/gxf-platform/templates/httpd/config.yaml
> +  vhosts.conf: |
Hetzelfde als bovenstaande een hele vhosts file embedded is misschien wat veel.

2025-03-20 11:31 UTC, paulusalliander commented on charts/gxf-platform/templates/config.yaml
> +  server.xml: |
Ook voor hier zo'n config file kan best groot worden, misschien is een externe file overwegen beter via --set-file. Bovendien kun je externe configuratie file reusen. Ik weet niet wat hier wijsheid is, volgens mij hebben wij de files ook embedded. Ik keur het in ieder geval nu goed.
https://devops.stackexchange.com/questions/18393/how-do-i-include-a-file-in-a-helm-config-map

2025-03-20 11:31 UTC, paulusalliander commented on charts/gxf-platform/template-apply.sh
> +#!/bin/bash
Zelfde als [bovenstaand template](https://github.com/OSGP/gxf-gitops/pull/1/files#diff-138505ec1131a7255de218c28f3df39c38334e5fbfc3d24be821e53a65c440f1)  m.u.v. van de naam osgp-platform toch? Van mij mag je deze generiek maken door een parameter toe te voegen. Ik keur het wel goed.

2025-03-20 12:38 UTC, JelleHoffman commented on generate-secrets.sh
> +  echo "sup3r_s3cr3t"
Ja in principe is dit zo, maar omdat het gaat om een test setup vonden we dit acceptabel. Deze secrets worden met iedere run gegeneerd. Ik gebruikte `dev/urandom` maar dat gaat niet in een GHA omgeving

2025-03-20 13:31 UTC, paulusalliander approved these changes
Perfect!

2025-03-20 14:07 UTC, smvdheijden commented on charts/gxf-platform/templates/httpd/config.yaml
> +      </Location>
I don't think this should be included here.

2025-03-20 14:16 UTC, smvdheijden approved these changes

2025-03-20 14:16 UTC, smvdheijden commented on charts/gxf-platform/values.yaml
> +#    readinessPort: 8080
As far as I know, we currently don't have a protocol simulator for IEC-61850, so this could probably be removed.

2025-03-20 14:16 UTC, smvdheijden commented on charts/gxf-platform/values.yaml
> +#  - name: osgp-web-device-simulator
Web device simulator is not needed for cucumber tests.

2025-03-21 15:25 UTC, smvdheijden requested changes

2025-03-21 15:25 UTC, smvdheijden commented on charts/gxf-platform/config/httpd/vhosts.conf
> +      ProxyPassReverse /sm-integration /sm-integration
Remove this.

2025-03-21 15:25 UTC, smvdheijden commented on charts/gxf-platform/config/httpd/httpd.conf
> +Include /usr/local/apache2/conf/vhosts.conf
no newline at end of file?

2025-03-21 15:25 UTC, smvdheijden commented on charts/gxf-platform/config/httpd/vhosts.conf
> +</VirtualHost>
no newline at end of file?

2025-03-21 15:25 UTC, smvdheijden commented on charts/gxf-platform/config/tomcat/server.xml
> +</Server>
no newline at end of file?

2025-03-21 15:39 UTC, smvdheijden approved these changes

2025-03-21 15:39 UTC, merged